### ISSUE TITLE
template<class> class std::auto_ptr’ is deprecated

### ISSUE THREAD

**Issue by jg-you** [mapequation/infomap#1]
Just a heads up, there is _a lot_ of  [-Wdeprecated-declarations] popping up when one compiles with `gcc 6.1.1` (i.e. using the 0x standard).
For instance:

    src/infomap/TreeData.h:140:7: warning: ‘template<class> class std::auto_ptr’ is deprecated 
    [-Wdeprecated-declarations]
    std::auto_ptr<NodeFactoryBase> m_nodeFactory;
 
Consider using `std::unique_ptr` or `std::shared_ptr` in newer versions.

**Comment by danieledler** [comment]
Thanks for the heads up, I just installed gcc6 to recreate this issue. We are working on a major internal update of the code, which uses the newer standard.
