### ISSUE TITLE
Method `add_link` throws error when type of `weight` argument is `numpy.int64`

### ISSUE THREAD

**Issue by ulfaslak** [mapequation/infomap#107]
Good job on the new API. I'll post issues as I run into bugs and problems using the new version. Here's the first problem I had:

When using `im.add_link`, if the `weight` parameter is given a np.int64 type value it throws the error:

```Python
~/.local/lib/python3.7/site-packages/infomap.py in add_link(self, source_id, target_id, weight)
   3243         weight : float, optional
   3244         """
-> 3245         return super().addLink(source_id, target_id, weight)
   3246 
   3247     def add_links(self, links):

~/.local/lib/python3.7/site-packages/infomap.py in addLink(self, sourceId, targetId, weight)
   2971 
   2972     def addLink(self, sourceId, targetId, weight=1.0):
-> 2973         return _infomap.InfomapWrapper_addLink(self, sourceId, targetId, weight)
   2974 
   2975     def addMultilayerLink(self, layer1, n1, layer2, n2, weight=1.0):

TypeError: Wrong number or type of arguments for overloaded function 'InfomapWrapper_addLink'.
  Possible C/C++ prototypes are:
    infomap::InfomapWrapper::addLink(unsigned int,unsigned int,double)
    infomap::InfomapWrapper::addLink(unsigned int,unsigned int)
```

Here's a minimal example that reproduces the error:

```Python
from infomap import Infomap

myweight = np.array([1])[0]
print(type(myweight)  # numpy.int64

im = Infomap('--two-level')
im.add_link(1, 2, myweight)
im.run()
im.modules
```

Note this DOES NOT happen if the input value is of type `np.float64`, `int` or `float`.

**Comment by danieledler** [comment]
Thanks for your valuable testing and feedback Ulf! We will fix it in the next patch release, probably tomorrow!

**Comment by danieledler** [comment]
Now it's up on PyPI, in version 1.0.6. Please try!

**Comment by ulfaslak** [comment]
It works, thanks!

**Comment by ulgenklc** [comment]
Hello,

I am still running into this issue in the multilayer case although I am using the 2.7.1 version in the HPC environment. I tried both `np.float` and `float` for interlayer link weights, however I'm getting the following error.

Here's the minimal example:

```
r = 0.1
num_layers = 6
adjacencies = [np.random.rand(100).reshape(10,10) for l in range(num_layers)]
IM = Infomap(directed = True, silent = True, two_level = True, multilayer_relax_rate = 0.2)
for l in range(length):
                for n1,e in enumerate(adjacencies[l]):
                    for n2,w in enumerate(e):
                        s = MultilayerNode(layer_id = l, node_id = n1)
                        t = MultilayerNode(layer_id = l, node_id = n2)
                        IM.add_multilayer_link(s, t, np.float64(adjacencies[l][n1][n2]))
                        IM.add_multilayer_link(t, s, np.float64(adjacencies[l][n1][n2]))
```

Error:

`multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/projects/academic/smuldoon/bengieru/anaconda/envs/gt/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/projects/academic/smuldoon/bengieru/anaconda/envs/gt/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/projects/academic/smuldoon/bengieru/Community_Detection/general_diagnostics_03/helpers.py", line 107, in run_infomap
    IM.add_multilayer_link(s, t, np.float64(w))
  File "/projects/academic/smuldoon/bengieru/anaconda/envs/gt/lib/python3.10/site-packages/infomap.py", line 4620, in add_multilayer_link
    return super().addMultilayerLink(
  File "/projects/academic/smuldoon/bengieru/anaconda/envs/gt/lib/python3.10/site-packages/infomap.py", line 3586, in addMultilayerLink
    return _infomap.InfomapWrapper_addMultilayerLink(
TypeError: Wrong number or type of arguments for overloaded function 'InfomapWrapper_addMultilayerLink'.
  Possible C/C++ prototypes are:
    infomap::InfomapWrapper::addMultilayerLink(unsigned int,unsigned int,unsigned int,unsigned int,double)
    infomap::InfomapWrapper::addMultilayerLink(unsigned int,unsigned int,unsigned int,unsigned int)

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/academic/smuldoon/bengieru/Community_Detection/general_diagnostics_03/G_T_ESCR_2/Infomap/G_T_ESCR_2_Infomap_multi.py", line 69, in <module>
    result = pool.starmap(run_infomap, inpts)
  File "/projects/academic/smuldoon/bengieru/anaconda/envs/gt/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/projects/academic/smuldoon/bengieru/anaconda/envs/gt/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
TypeError: Wrong number or type of arguments for overloaded function 'InfomapWrapper_addMultilayerLink'.
  Possible C/C++ prototypes are:
    infomap::InfomapWrapper::addMultilayerLink(unsigned int,unsigned int,unsigned int,unsigned int,double)
    infomap::InfomapWrapper::addMultilayerLink(unsigned int,unsigned int,unsigned int,unsigned int)`

**Comment by danieledler** [comment]
Hi @ulgenklc, unfortunately I can't reproduce the error from the minimum example. I tried Python 3.10 and 3.11 on MacOS. I guess you run this on Linux? Can you reproduce the error on other platforms?

**Comment by ulgenklc** [comment]
Hi Daniel

Sorry, this is absolutely my bad! You are right, my minimal example doesn't generate the error. But the following should:

`from infomap import Infomap, MultilayerNode

num_layers = 6
num_nodes = 10
adjacencies = [np.random.rand(100).reshape(num_nodes,num_nodes) for l in range(num_layers)]

IM = Infomap(directed = True, silent = True, two_level = True, multilayer_relax_rate = 0.2)

for l in range(num_layers):
      for n1,e in enumerate(adjacencies[l]):
            for n2,w in enumerate(e):
                  s = MultilayerNode(layer_id = l, node_id = n1)
                  t = MultilayerNode(layer_id = l, node_id = n2)
                  IM.add_multilayer_link(s, t, np.float64(w))
                  IM.add_multilayer_link(t, s, np.float64(w))

inter_edge_weight = 1
for l in range(num_layers-1):
      for n in range(num_nodes):
                  s = MultilayerNode(layer_id = l, node_id = n)
                  t = MultilayerNode(layer_id = l+1, node_id = n)
                  IM.add_multilayer_link(s, t, np.float64(inter_edge_weight))
                  IM.add_multilayer_link(t, s, np.float64(inter_edge_weight))
`
Naturally, `l+1` is not an integer anymore and it becomes a `float`, so doing `int(l+1)` fixes it.

Thank you for your quick reply!

**Comment by danieledler** [comment]
My environment seems to be a bit more forgiving as `l+1` becomes an int and `l+1.`, which becomes a float, somehow works too. Actually `l+1.000000000000001` works too, but not `l+1.00000000000001`. With e-notation I can't add even the smallest float. But good that you found the solution. 👍
