### ISSUE TITLE
make python fails: gcc unrecognized command line option '-02'

### ISSUE THREAD

**Issue by FilipMiscevic** [mapequation/infomap#11]
When I try to make with the python wrapper, I get the following error:

> make python
> swig -c++ -python -outdir build/py -o build/py/infomap_wrap.cpp build/py/Infomap.i
> src/utils/Date.h:96: Warning 362: operator= ignored
> src/io/Config.h:283: Warning 362: operator= ignored
> src/infomap/Network.h:141: Warning 362: operator= ignored
> src/infomap/MemNetwork.h:170: Warning 362: operator= ignored
> src/io/HierarchicalNetwork.h:178: Warning 362: operator= ignored
> src/io/HierarchicalNetwork.h:435: Warning 362: operator= ignored
> src/io/HierarchicalNetwork.h:491: Warning 383: operator++ ignored
> src/io/HierarchicalNetwork.h:499: Warning 383: operator++ ignored
> src/io/HierarchicalNetwork.h:577: Warning 362: operator= ignored
> src/io/HierarchicalNetwork.h:642: Warning 383: operator++ ignored
> src/io/HierarchicalNetwork.h:650: Warning 383: operator++ ignored
> src/io/HierarchicalNetwork.h:728: Warning 362: operator= ignored
> src/io/HierarchicalNetwork.h:763: Warning 383: operator++ ignored
> src/io/HierarchicalNetwork.h:771: Warning 383: operator++ ignored
> src/io/HierarchicalNetwork.h:510: Warning 508: Declaration of 'depth' shadows declaration accessible via operator->(),
> src/io/HierarchicalNetwork.h:222: Warning 508: previous declaration of 'depth'.
> src/io/HierarchicalNetwork.h:661: Warning 508: Declaration of 'depth' shadows declaration accessible via operator->(),
> src/io/HierarchicalNetwork.h:222: Warning 508: previous declaration of 'depth'.
> src/utils/Date.h:83: Warning 503: Can't wrap 'operator <<' unless renamed to a valid identifier.
> src/utils/Date.h:115: Warning 503: Can't wrap 'operator <<' unless renamed to a valid identifier.
> cd build/py && python setup.py build_ext --inplace
> running build_ext
> building '_infomap' extension
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -fopenmp -02 -march=core2 -ftree-vectorize -fPIC -I/usr/include/python2.7 -c ./infomap_wrap.cpp -o build/temp.linux-x86_64-2.7/./infomap_wrap.o -DAS_LIB
**> x86_64-linux-gnu-gcc: error: unrecognized command line option ‘-02’**
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> Makefile:139: recipe for target 'python' failed
> make: *** [python] Error 1

**Comment by danieledler** [comment]
It's -02 but should be -O2 (big o instead of a zero). As this is not set in the Infomap library, probably it is picked up by the environment variable CFLAGS that have that error in your environment for some reason. What is your operating system and version?

**Comment by FilipMiscevic** [comment]
Thank you - I read about a similar issue in other posts. However, -O2 is already a flag used above... is the -02 related to -fopenmp maybe? I am using Ubuntu 16.04.
