### ISSUE TITLE
TypeError: 'Network' object is not callable

### ISSUE THREAD

**Issue by Niko-shvets** [mapequation/infomap#114]
Hi,

Appeared this error: TypeError: 'Network' object is not callable

but code worked before 

TypeError                                 Traceback (most recent call last)
<ipython-input-25-39cfb13ef9fe> in <module>()
      1 weights_matrix=np.matrix(weights_1)
      2 Graph=nx.DiGraph(weights_matrix)
----> 3 findCommunities(Graph)
      4 communities = [v for k,v in nx.get_node_attributes(Graph, 'community').items()]
      5 print('number of clusters:', np.unique(communities))

<ipython-input-22-5d6e48bf3702> in findCommunities(G)
      8     print("Building Infomap network from a NetworkX graph...")
      9     for e in G.edges():
---> 10         infomapX.network().addLink(*e)
     11 
     12     print("Find communities with Infomap...")

TypeError: 'Network' object is not callable

**Comment by danieledler** [comment]
Hi,

Thanks for your feedback, probably you just discovered that we recently updated the python API a bit when we moved to version 1.0, so for example the `network()` function changed to a `network` getter. We have documented the new python API [here](https://mapequation.github.io/infomap/python/).

Similar issue: #105.
