### ISSUE TITLE
Infomap 1.0 not creating .clu file

### ISSUE THREAD

**Issue by iamdamion** [mapequation/infomap#13]
I have used previous versions of infomap in the past for a few projects and it's worked wonderfully. However, I had to download it to a new computer and downloaded/installed it from the current link on the mapequation website. It appeared to work as normal with my pajek file, but now I've noticed that using the --clu option doesn't produce a cluster file. I'm actually only able to get a .tree file out. Even when specifying all of the print options. 

I believe this is an issue with the newest version? (the download link was created a few days ago according to the download folder). Any help would be greatly appreciated.

**Comment by danieledler** [comment]
Thanks for the quick feedback, my mistake. That version was not ready to replace the previous yet, but now the download link should point to the stable version again.
