### ISSUE TITLE
Support JSON output

### ISSUE THREAD

**Issue by antoneri** [mapequation/infomap#132]
To speed up the web applications (navigator, alluvial), it would be nice to output JSON from Infomap. This would make the npm package [infoparse](https://www.npmjs.com/package/@mapequation/infoparse) redundant.

The format could look something like this:

```json
{
  "version": "1.1.0",
  "arguments": "./Infomap network.net . -o json",
  "startedAt": "2020-03-30 22:07:26", // "unix timestamp instead?"
  "completedIn": 0.114, // "implied to be seconds"
  "numLevels": 2,
  "numTopModules": 2,
  "codelength": 2.32073, // "bits"
  "relativeCodelengthSavings": 0.09227, // "instead of percent"
  "directed": true,
  "nodes": {
    "1": { // "id or path?"
      "path": "1:1", // "id if we use path above"
      "flow": 0.123,
      "name": "BIOL A",
    }
  },
  "modules": {
    "1": { // "path"
      "enterFlow": 0.1,
      "exitFlow": 0.1,
      "numEdges": 2, // "or links?"
      "numChildren": 23
    }
  },
  "links": { // "optionally included"
    "1": [ // "path"
      {
        "source": 1,
        "target": 2,
        "flow": 0.1
      }
    ]
  }
}
```

**Comment by chrisbloecker** [comment]
Some thoughts:
- Avoid spaces in keys, use _camelCase_ or _snake_case_.
- Why not represent the community structure as nested JSON objects?
- Is the number of top level modules interesting enough to mention it? If we represent the community structure as a tree, it's easy to figure out the number of top level modules.
- _Relative codelength savings_ is not very descriptive, maybe we should call it _compression_ or something like that.
- I like the idea to include a link list in the output, but do we want that in all cases (i.e. *large* networks)? I think it should be optional.

Community structure as nested JSON objects:
```
{
  "1": {
    "1": 1,
    "2": 2,
    "3": 3
  },
  "2": {
    "1": 4,
    "2": 5,
    "3": 6
  }
}
```
And we could expand this to contrain information like enterFlow, exitFlow,...

**Comment by antoneri** [comment]
>     * Avoid spaces in keys, use _camelCase_ or _snake_case_.
Good idea.
>     * Is the number of top level modules interesting enough to mention it? If we represent the community structure as a tree, it's easy to figure out the number of top level modules.
This is to keep the same information that is provided in the other formats, which has been requested by a user.
>     * _Relative codelength savings_ is not very descriptive, maybe we should call it _compression_ or something like that.
Maybe, we have rejected that name in the past.
>     * I like the idea to include a link list in the output, but do we want that in all cases (i.e. _large_ networks)? I think it should be optional.
Yes, links are optionally included.

**Comment by chrisbloecker** [comment]
Doing something like

```python
for path, (id, name, flow) in nodes.items():
```

would indeed need a little bit more work, but I think it wouldn't be overly complicated. One could implement a generic interpreter that takes a function and traverses the module structure to apply that function to each leaf node (I think only the leaves are of interest). Such a function could, for example, `yield` a tuple with the above-mentioned properties and turn the object into a generator.

But of course both structures are isomorphic and the question is "What do most people want to do with the modules?". Perhaps some users would like to know which nodes are in the module with path `1:2:3`.
