### ISSUE TITLE
how to set number of cores used when executing run method?

### ISSUE THREAD

**Issue by RaulGuo** [mapequation/infomap#134]
I am using Infomap v1.1.2. I found that when executing run method, there is only one cpu used with almost 100%, the left ones are not used at all. Is there a way to use multi cores to execute run() method to speed up the calculation? there are 1.5 billions edges added to network. 

```
two_level_infomap = infomap.Infomap("--two-level")
# 1.5 billion edges
two_level_infomap.add_links(edges)
two_level_infomap.run()
```

**Comment by antoneri** [comment]
Hi and thanks for reaching out.

Are you using Mac, Windows och Linux? For Mac-users we offer a precompiled binary which at the moment doesn't support parallelisazion. We will fix this as soon as possible!

**Comment by antoneri** [comment]
Are you using the flag `--inner-parallelization` by the way?

See [the documentation](https://www.mapequation.org/infomap/#Parameters) under "Accuracy" and toggle "Show advanced parameters".
