### ISSUE TITLE
v1 cli support

### ISSUE THREAD

**Issue by danieledler** [mapequation/infomap#14]
Support of old CLI:

- [ ] --input-format
  - [x] pajek
  - [x] link-list
  - [x] states
  - [ ] ~~3gram~~
  - [x] n-gram
  - [x] multilayer
  - [x] ~~bipartite~~ (v1.1)
- [ ] ~~--with-memory~~ (move to Infomap Utils)
- [ ] ~~--multilayer-add-missing-nodes~~
- [ ] ~~--skip-adjust-bipartite-flow~~ (adjust with --markov-time)
- [ ] ~~--overlapping~~ (same as --with-memory)
- [x] --hard-partitions
- [ ] ~~--non-backtracking~~ (move to Infomap Utils)
- [ ] ~~--without-iostream~~
- [ ] ~~--zero-based-numbering~~
- [x] --include-self-links
- [ ] ~~--complete-dangling-memory-nodes~~ (move to Infomap utils)
- [ ] --node-limit <n> (move to Infomap utils)
- [ ] --weight-threshold <n> (move to Infomap utils)
- [ ] --pre-cluster-multiplex (evaluate)
- [ ] --cluster-data <p>
  - [ ] .tree
  - [x] .clu
- [x] --no-infomap
- [x] --out-name
- [x] --no-file-output
- [x] --map
- [x] --clu
- [x] --tree
- [ ] ~~--ftree~~ (v1.1)
- [ ] ~~--btree~~ (v1.1)
- [ ] ~~--bftree~~ (v1.1)
- [ ] ~~--node-ranks~~ (move to Infomap Utils)
- [ ] ~~--flow-network~~ (move to Infomap Utils)
- [ ] ~~--pajek~~ (move to Infomap Utils)
- [ ] ~~--print-state-network~~ (move to Infomap Utils)
- [ ] --expanded (update explanation to highlight that it's the output .tree/.clu that changes)
- [x] --two-level
- [x] --dynamics
  - [x] undirected
  - [x] directed
  - [x] undirdir
  - [x] outdirdir
  - [x] rawdir
- [x] ~~--recorded-teleportation~~
- [x] ~~--to-nodes~~
- [x] --teleportation-probability <f>
- [ ] ~~--self-link-teleportation-probability <f>~~ (Use --markov-time)
- [ ] --markov-time <f> (Add simulation to Infomap Utils)
- [ ] --variable-markov-time
- [ ] ~~--preferred-number-of-modules <n>~~ (Not optimized)
- [ ] --multilayer-relax-rate <f>
- [ ] --multilayer-relax-limit <n>
- [ ] --multilayer-js-coupling
- [ ] ~~--multilayer-js-relax-rate <f>~~
- [ ] ~~--multilayer-js-relax-limit <f>~~
- [ ] ~~--multiplex-relax-rate <f>~~
- [ ] ~~--multiplex-js-relax-rate <f>~~
- [ ] ~~--multiplex-js-relax-limit <f>~~
- [ ] ~~--multiplex-relax-limit <n>~~
- [x] --seed <n>
- [x] --num-trials <n>
- [x] --min-improvement <f>
- [x] --random-loop-limit
- [x] --core-loop-limit <n>
- [x] --core-level-limit <n>
- [x] --tune-iteration-limit <n>
- [x] --tune-iteration-threshold <f>
- [ ] ~~--fast-first-iteration~~
- [ ] ~~--fast-coarse-tune~~
- [ ] ~~--alternate-coarse-tune-level~~
- [ ] ~~--coarse-tune-level <n>~~
- [ ] --fast-hierarchical-solution [+]
- [x] ~~--skip-replace-to-one-module~~
- [ ] ~~--low-memory [+]~~
- [ ] ~~--inner-parallelization~~ (later version)
- [ ] ~~--reset-options-before-recursion~~
- [ ] ~~--show-bipartite-nodes~~
- [x] --verbose [+]
- [x] --silent

**Comment by tduberne** [comment]
Am I right if I understand that the `--multilayer-js-relax-rate` functionality will be abandoned in v1.x?

I just tried to use it from the Python version available on Pypi, to no avail. Not a big issue, I will just revert to using v0.xx from the command line, but I would like to know what I can expect from the python side in a close future.

**Comment by danieledler** [comment]
No it will be implemented very soon, I see we renamed it to `--multilayer-js-coupling` above, but for now you have to use the v0.x version.

**Comment by tduberne** [comment]
Ok, great, thank you for the information!
