### ISSUE TITLE
segmentation fault error when using --directed option

### ISSUE THREAD

**Issue by kayamin** [mapequation/infomap#15]
Hi,
I'm trying to use your implementation of infomap algorithm on directed weighted graph with networkx.
However when I run code with --directed option, I got segmentation fault either at  infomap/examples/cpp/minimal/example.cpp, infomap/examples/python/example-networkx.py

Would you please give me some idea to solve this ?? 

> =======================================================
  Infomap v0.19.11 starts at [2017-11-26 21:53:59]
  -> Configuration: two-level
                    directed
                    num-trials = 2
  -> Use directed flow and 1st order Markov dynamics with unrecorded teleportation to links
=======================================================
Finalizing network...
 ==> 6 nodes and 14 links.
Calculating global flow...
  -> Using unrecorded teleportation to links. [1]    82113 segmentation fault (core dumped)  ./example

**Comment by danieledler** [comment]
Should be fixed now, but please comment further if you have any problems.

**Comment by kayamin** [comment]
Thank you for a prompt reply.
I should have inspect more detail before raising issue. m(_ _)m
