### ISSUE TITLE
infomap '1.2.0' python pip package installation fails in Windows 10: needs #include <algorithm> line

### ISSUE THREAD

**Issue by ati-ozgur** [mapequation/infomap#150]
pip install infomap 

command in windows fails with "Error C2039: 'max' : is not a member of 'std'" error.
Please make the following 1 line change

diff --git a/src/io/ClusterReader.cpp b/src/io/ClusterReader.cpp
index 85e49af..8882134 100644
--- a/src/io/ClusterReader.cpp
+++ b/src/io/ClusterReader.cpp
@@ -24,6 +24,7 @@

 **********************************************************************************/

+#include <algorithm>

 #include "ClusterReader.h"
 #include "../utils/Log.h"

**Comment by antoneri** [comment]
Thanks for reaching out! We'll fix that as soon as possible.
