### ISSUE TITLE
multiplex-js-relax-rate option disabled

### ISSUE THREAD

**Issue by michelegirolami** [mapequation/infomap#154]
Hi all,

I tried to run Infomap 1.2.0 by using the multiplex-js-relax-rate for the coupling nodes based on the Jensen-Shannon divergence. This option was available with Infomap 0.20 but it seems now disabled. 
I tired to uncomment the option from the src/io/Config.cpp:
 ```
 //TODO: Add for v1.x
  // api.addOptionArgument(conf.multilayerRelaxByJensenShannonDivergence, "multilayer-relax-by-jsd",
  //         "Relax proportional to the out-link similarity measured by the Jensen-Shannon divergence.", ArgType::number, "Algorithm", true);

  api.addOptionArgument(conf.multilayerJSRelaxRate, "multilayer-js-relax-rate",
          "The probability to relax the constraint to move only in the current layer and instead move to a random layer where the same physical node is present and proportional to the out-link similarity measured by the Jensen-Shannon divergence.", ArgType::probabilities"Algorithm", true);

  api.addOptionArgument(conf.multilayerJSRelaxLimit, "multilayer-js-relax-limit",
          "The minimum out-link similarity measured by the Jensen-Shannon divergence to relax to other layer. From 0 to 1. No limit if negative.", ArgType::integer, "Algorithm", true);
```
and replacing ArgType::getprop to: ArgType::probabilities and ArgType::integer for js-relax-rate and js-relax-limit respectively.  Compilation succeeds, however it seems that the option does not work. In particular, by varying the js-relax-rate from 0 to 1 I obtain always the same number of modules  with the same codelength. Differenrly, by using the multiplex-relax-rate (without JS divergence) I obtain different modules as expected.

Would it possible to re-introduce such option? If no, is there any other change to implement in order to have the option compiled locally? Maybe I simply enabled the option but the code implementing the node coupling is not invoked.... 

let me know is possible.

Thanks

**Comment by danieledler** [comment]
Thanks for your interest and digging into the Infomap code, we will fix this later today or early next week!

**Comment by michelegirolami** [comment]
> 
> 
> Thanks for your interest and digging into the Infomap code, we will fix this later today or early next week!

This is awesome. Thanks and If I can support you somehow please let me know

**Comment by danieledler** [comment]
Hi, unfortunately I got a bit delayed but hopefully the implementation should work later tomorrow.

**Comment by danieledler** [comment]
I just pushed an implementation to the `fix/js-relax` branch, sorry again for the delay. I am not done testing it though, but if you want you are very welcome to test it and see if the result already seem to make sense. The issue will be kept open until we have done some more thorough testing and merged it to the master branch.
