### ISSUE TITLE
windows python pip install infomap error: failed building the wheel

### ISSUE THREAD

**Issue by hexie1995** [mapequation/infomap#162]
Hello! I am using a windows 10 machine and I am trying to build infomap for python. I used both anaconda and the windows sub machine for Ubuntu and I used the command "pip install infomap" and "pip install --upgrade infomap", both give me the exact same error : failed to build the wheel. I am not sure the reason why, I have gcc installed and made sure that it is in the system variable. Would you mind explaining why this happened? Thank you!!

**Comment by antoneri** [comment]
Hi and thanks for reaching out!

Can you give us some more information? Which version of Python and GCC do you use?

**Comment by hexie1995** [comment]
Yes sure. Thanks for getting back to me so quickly. I am using Python 3.7.2 and gcc is the version of gcc is "mingw32-gcc-g++-bin".

**Comment by antoneri** [comment]
Can you please paste the full output of the error?

**Comment by hexie1995** [comment]
3.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tp./src\core\InfomapIterator.cpp /Fobuild\temp.win-amd64-3.7\Release\./src\core\InfomapIterator.obj /DAS_LIB /DPYTHON /DNOMINMAX
    InfomapIterator.cpp
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\../utils/MetaCollection.h(88): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfoNode.h(207): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfoNode.h(385): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfoNode.h(390): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\Users\hexie\Anaconda2\envs\python3\include -IC:\Users\hexie\Anaconda2\envs\python3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tp./src\core\InfoNode.cpp /Fobuild\temp.win-amd64-3.7\Release\./src\core\InfoNode.obj /DAS_LIB /DPYTHON /DNOMINMAX
    InfoNode.cpp
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\../utils/MetaCollection.h(88): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(207): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(385): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(390): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../utils/Date.h(89): warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\time.h(506): note: see declaration of 'localtime'
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\ProgramInterface.h(354): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\utils\MersenneTwister.h(233): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h(208): note: see declaration of 'fopen'
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\../utils/Random.h(98): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../core/StateNetwork.h(184): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../core/StateNetwork.h(185): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfomapOptimizer.h(181): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfomapOptimizer.h(180): note: while compiling class template member function 'unsigned int infomap::InfomapOptimizer<infomap::MetaMapEquation>::numActiveModules(void) const'
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfomapOptimizer.h(167): note: see reference to class template instantiation 'infomap::InfomapOptimizer<infomap::MetaMapEquation>' being compiled
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfomapOptimizer.h(550): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfomapOptimizer.h(538): note: while compiling class template member function 'unsigned int infomap::InfomapOptimizer<infomap::MetaMapEquation>::tryMoveEachNodeIntoBestModule(void)'
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfomapOptimizer.h(321): note: see reference to function template instantiation 'unsigned int infomap::InfomapOptimizer<infomap::MetaMapEquation>::tryMoveEachNodeIntoBestModule(void)' being compiled
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfomapOptimizer.h(775): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfomapOptimizer.h(730): note: while compiling class template member function 'unsigned int infomap::InfomapOptimizer<infomap::MetaMapEquation>::tryMoveEachNodeIntoBestModuleInParallel(void)'
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\InfomapOptimizer.h(321): note: see reference to function template instantiation 'unsigned int infomap::InfomapOptimizer<infomap::MetaMapEquation>::tryMoveEachNodeIntoBestModuleInParallel(void)' being compiled
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\Users\hexie\Anaconda2\envs\python3\include -IC:\Users\hexie\Anaconda2\envs\python3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tp./src\core\MapEquation.cpp /Fobuild\temp.win-amd64-3.7\Release\./src\core\MapEquation.obj /DAS_LIB /DPYTHON /DNOMINMAX
    MapEquation.cpp
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../utils/Date.h(89): warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\time.h(506): note: see declaration of 'localtime'
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\ProgramInterface.h(354): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\../utils/MetaCollection.h(88): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(207): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(385): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(390): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\Users\hexie\Anaconda2\envs\python3\include -IC:\Users\hexie\Anaconda2\envs\python3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tp./src\core\MemMapEquation.cpp /Fobuild\temp.win-amd64-3.7\Release\./src\core\MemMapEquation.obj /DAS_LIB /DPYTHON /DNOMINMAX
    MemMapEquation.cpp
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../utils/Date.h(89): warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\time.h(506): note: see declaration of 'localtime'
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\ProgramInterface.h(354): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\../utils/MetaCollection.h(88): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(207): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(385): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(390): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\core\MemMapEquation.cpp(85): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\core\MemMapEquation.cpp(141): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\core\MemMapEquation.cpp(272): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\Users\hexie\Anaconda2\envs\python3\include -IC:\Users\hexie\Anaconda2\envs\python3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tp./src\core\MetaMapEquation.cpp /Fobuild\temp.win-amd64-3.7\Release\./src\core\MetaMapEquation.obj /DAS_LIB /DPYTHON /DNOMINMAX
    MetaMapEquation.cpp
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../utils/Date.h(89): warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\time.h(506): note: see declaration of 'localtime'
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\ProgramInterface.h(354): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\../utils/MetaCollection.h(88): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(207): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(385): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\InfoNode.h(390): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\Users\hexie\Anaconda2\envs\python3\include -IC:\Users\hexie\Anaconda2\envs\python3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tp./src\core\StateNetwork.cpp /Fobuild\temp.win-amd64-3.7\Release\./src\core\StateNetwork.obj /DAS_LIB /DPYTHON /DNOMINMAX
    StateNetwork.cpp
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../utils/Date.h(89): warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\time.h(506): note: see declaration of 'localtime'
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\ProgramInterface.h(354): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\StateNetwork.h(184): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    headers/src/core\StateNetwork.h(185): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\Users\hexie\Anaconda2\envs\python3\include -IC:\Users\hexie\Anaconda2\envs\python3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tp./src\io\BipartiteClusterReader.cpp /Fobuild\temp.win-amd64-3.7\Release\./src\io\BipartiteClusterReader.obj /DAS_LIB /DPYTHON /DNOMINMAX
    BipartiteClusterReader.cpp
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\../utils/MetaCollection.h(88): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../core/InfoNode.h(207): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../core/InfoNode.h(385): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../core/InfoNode.h(390): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\Users\hexie\Anaconda2\envs\python3\include -IC:\Users\hexie\Anaconda2\envs\python3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tp./src\io\ClusterReader.cpp /Fobuild\temp.win-amd64-3.7\Release\./src\io\ClusterReader.obj /DAS_LIB /DPYTHON /DNOMINMAX
    ClusterReader.cpp
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\core\../utils/MetaCollection.h(88): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../core/InfoNode.h(207): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../core/InfoNode.h(385): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\hexie\appdata\local\temp\pip-install-k6qf4zwo\infomap\headers\src\io\../core/InfoNode.h(390): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\io\ClusterReader.cpp(177): error C2039: 'max': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\fstream(21): note: see declaration of 'std'
    ./src\io\ClusterReader.cpp(177): error C3861: 'max': identifier not found
    ./src\io\ClusterReader.cpp(212): error C2039: 'max': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\fstream(21): note: see declaration of 'std'
    ./src\io\ClusterReader.cpp(212): error C3861: 'max': identifier not found
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\hexie\Anaconda2\envs\python3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\hexie\\AppData\\Local\\Temp\\pip-install-k6qf4zwo\\infomap\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\hexie\AppData\Local\Temp\pip-record-dob18p90\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\hexie\AppData\Local\Temp\pip-install-k6qf4zwo\infomap\



Thanks for the response! Sorry for the back and forth. Here is almost everything I got. I also had one red line says "failed building the wheel" before I saw all these error messages.

**Comment by antoneri** [comment]
Thanks! This is helpful, we will begin working on a fix.

**Comment by antoneri** [comment]
Try again, we've released a bug fix just now.

Re-open the issue if you have any more problems!

(Fixed in 8e08309)

**Comment by hexie1995** [comment]
Thank you very much for your help! It worked!

**Comment by pamphilusTex** [comment]
Hello! I am using a windows 10 machine and I am trying to build "infomap" for python. I am using anaconda (conda version 4.9.2, python version 3.7.9) and gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project). I used the command "pip install infomap" and "pip install --upgrade infomap", both give me the exact same error. Could you help me solve this problem? Thank you!

  ----------------------------------------
  ERROR: Failed building wheel for infomap
  Running setup.py clean for infomap
Failed to build infomap
Installing collected packages: infomap
    Running setup.py install for infomap ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Software\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'...\\Temp\\pip-install-e9p4lqce\\infomap\\setup.py'"'"'; __file__='"'"'...\\Temp\\pip-install-e9p4lqce\\infomap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record '...\Temp\pip-record-vmy4tc16\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Software\Anaconda3\Include\infomap'
         cwd: ...\Temp\pip-install-e9p4lqce\infomap\
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying infomap.py -> build\lib.win-amd64-3.7
    copying package_meta.py -> build\lib.win-amd64-3.7
    running egg_info
    writing infomap.egg-info\PKG-INFO
    writing dependency_links to infomap.egg-info\dependency_links.txt
    writing entry points to infomap.egg-info\entry_points.txt
    writing top-level names to infomap.egg-info\top_level.txt
    reading manifest file 'infomap.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'infomap.egg-info\SOURCES.txt'
    running build_ext
    building '_infomap' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    creating build\temp.win-amd64-3.7\Release\src\core
    creating build\temp.win-amd64-3.7\Release\src\io
    creating build\temp.win-amd64-3.7\Release\src\utils
    C:\Software\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\Software\Anaconda3\include -IC:\Software\Anaconda3\include -c ./infomap_wrap.cpp -o build\temp.win-amd64-3.7\Release\.\infomap_wrap.o /DAS_LIB /DPYTHON /DNOMINMAX
    gcc: error: /DAS_LIB: No such file or directory
    gcc: error: /DPYTHON: No such file or directory
    gcc: error: /DNOMINMAX: No such file or directory
    error: command 'C:\\Software\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe' failed with exit status 1

**Comment by JoeJoe1313** [comment]
@pamphilusTex, did you manage to resolve your issue? I had the same problem on macOS with this python version but I had no problem when I used Python 3.8.5.
