### ISSUE TITLE
.edges_iter no longer available in networkx 2.0

### ISSUE THREAD

**Issue by sebacea** [mapequation/infomap#17]
it seems that .edges_iter no longer exists so python examples are not working

**Comment by danieledler** [comment]
Thanks for the notice!

**Comment by sebacea** [comment]
so, any advice to work in python?

**Comment by danieledler** [comment]
Did you get the python example to work now with the commit above?

**Comment by sebacea** [comment]
example-networkx.py works fine, but findCommunities() y drawNetwork should be updated in the same way in infomap-examples.ipynb

**Comment by danieledler** [comment]
Thanks!

**Comment by danieledler** [comment]
I may add that we are working on a new version that may have a slightly different API but with that we will also document the API which is lacking now.
