### ISSUE TITLE
Can attach the python API pages

### ISSUE THREAD

**Issue by mindayao** [mapequation/infomap#170]
I want to learn this algorithm, but i can't load the python api pages

**Comment by danieledler** [comment]
Oh, thank you for the heads-up! We will try to fix it as soon as possible and give you a notice when it works.

**Comment by danieledler** [comment]
Hi again @mindayao, now it is fixed, so please try reload the page. If it is still the same, there may be some dns propagation delay depending on where you are but should work in a couple of hours.
