### ISSUE TITLE
error building infomap via PyPI on a cluster

### ISSUE THREAD

**Issue by ulgenklc** [mapequation/infomap#171]
I'm trying to install infomap's python distribution on a conda environment in a linux cluster. `pip install infomap` yields the following error. Is there a way to install infomap via anaconda? I feel like that would solve the problem. If not, do you know why I'm getting this error?

```
ERROR: Command errored out with exit status 1:
   command: /projects/academic/smuldoon/bengieru/anaconda/envs/ulgenv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-ins
tall-bmrmja7n/infomap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bmrmja7n/infomap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);co
de=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vyf5448r
       cwd: /tmp/pip-install-bmrmja7n/infomap/
  Complete output (25 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  copying infomap.py -> build/lib.linux-x86_64-3.7
  copying package_meta.py -> build/lib.linux-x86_64-3.7
  running egg_info
  writing infomap.egg-info/PKG-INFO
  writing dependency_links to infomap.egg-info/dependency_links.txt
  writing entry points to infomap.egg-info/entry_points.txt
  writing top-level names to infomap.egg-info/top_level.txt
  reading manifest file 'infomap.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'infomap.egg-info/SOURCES.txt'
  running build_ext
  building '_infomap' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  creating build/temp.linux-x86_64-3.7/src/core
  creating build/temp.linux-x86_64-3.7/src/io
  creating build/temp.linux-x86_64-3.7/src/utils
  gcc -pthread -B /projects/academic/smuldoon/bengieru/anaconda/envs/ulgenv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall 
-Wstrict-prototypes -fPIC -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -I/projects/academic/smuldoon/bengieru/anaconda
/envs/ulgenv/include/python3.7m -c ./infomap_wrap.cpp -o build/temp.linux-x86_64-3.7/./infomap_wrap.o -DAS_LIB -DPYTHON -Wno-deprecated-register -std=c++
14
  gcc: error: unrecognized command line option ‘-std=c++14’
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for infomap
  Running setup.py clean for infomap
Failed to build infomap
```

**Comment by antoneri** [comment]
Hi and thanks for reaching out!

Can you please specify which version of Python and GCC you are using?

**Comment by ulgenklc** [comment]
Ahh I see. I can't use an unmaintained version then..

It's Python 3.7.9 and this is what `gcc -v` returns:

`
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-
bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enab
le-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin 
--enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/b
uild/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_
64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) `

Thank you for the quick response!

**Comment by antoneri** [comment]
I don't have a solution yet, but it usually compiles with g++, not gcc.

**Comment by antoneri** [comment]
Also noting that your GCC version is from 2015, and Infomap requires c++14, so that could be the problem.

**Comment by ulgenklc** [comment]
Okay, I am gonna try to have GCC be updated and try again. I'll keep you updated.

Thank you!

Ülgen

**Comment by ulgenklc** [comment]
Like you said, it was because of the old version of GCC which was by default older version, when I load the newer version module, it is all built.

Thank you for your time!
