### ISSUE TITLE
Doesn't give communities with a weighted network.

### ISSUE THREAD

**Issue by isukrit** [mapequation/infomap#18]
Hi, I have a undirected, fully-connected, weighted network with 264 nodes. The edge weights represent weights (importance of links) and not the distance between nodes. I ran the algorithm, but it gives me 264 clusters even after 100 trials. I am attaching the adjacency matrix for your consideration. Can you pinpoint what the issue might be? 

[averaged_matrix_weighted.csv.zip](https://github.com/mapequation/infomap/files/1697836/averaged_matrix_weighted.csv.zip)

**Comment by mrosvall** [comment]
Infomap takes a link list or Pajek network as input, see http://www.mapequation.org/code.html#Input Please share the input file that you used, and we will try to figure out what goes on.

**Comment by isukrit** [comment]
I did share the relevant file with you (CSV). I took the input file and converted it into a networkx graph. That's what I fed to the network.

**Comment by isukrit** [comment]
file = "averaged_matrix_weighted.csv"
csvfile = open(file, 'rb')
data = np.genfromtxt(csvfile, delimiter=',', dtype=None)
g  = nx.Graph()
g.add_nodes_from(list (range (0, 264)))
graph_data = data/np.max(data)
threshold = 0
distance_data = 1 - data/np.max(data)	 #dissimilarity or distance	


for i1, data1 in enumerate(graph_data):
	for i2, data2 in enumerate(graph_data):
		if graph_data[i1][i2] < threshold and graph_data[i1][i2] != inf:
			graph_data[i1][i2], graph_data[i2][i1] = 0, 0
		else:
			g.add_edge(i1, i2, weight = graph_data[i1][i2])


Now, you've read the file and fed it into a networkX graph. You can proceed further from here.

**Comment by isukrit** [comment]
I tried to take PAJEK network input as well. Attached the file. Still gives the same result. 
[group_network.net.zip](https://github.com/mapequation/infomap/files/1699079/group_network.net.zip)

**Comment by mrosvall** [comment]
I get 1 cluster with the .net file. Do you expect a group structure? Perhaps a different link pruning?

**Comment by isukrit** [comment]
Yes, there should be a group structure. I detected 8 clusters with Louvain. 

What do you mean by 'link pruning'? Is it something like thresholding to reduce the number of links? I got the above results with the same file (without thresholding).

**Comment by danieledler** [comment]
Yes you have to increase the threshold a little bit for Infomap to find non-trivial modules. The two algorithms make different trade-offs, which for the number of modules is more apparent close to fully connected and fully disconnected networks: https://gist.github.com/danieledler/75592416d34f59e855c1b62ba0c90ff6

Note that they follow each other pretty close for threshold values between 0.05 and 0.3.

**Comment by ann644ie** [comment]
> Yes, there should be a group structure. I detected 8 clusters with Louvain.
> 
> What do you mean by 'link pruning'? Is it something like thresholding to reduce the number of links? I got the above results with the same file (without thresholding).

>Hi, do you know which community discovery algorithm will be best and fast when we want to give number of communities we want initially. Graph given is weighted and undirected. In my dataset I want 2 communities and I am getting 27 by using Louvian algorithm.
