### ISSUE TITLE
ImportError: cannot import name 'Infomap' from 'infomap' in .py but it works in cmd

### ISSUE THREAD

**Issue by zhangbw17** [mapequation/infomap#186]
I was faced with a very strange problem.
When I ran `from infomap import Infomap` in a .py file in pycharm or command line, it failed with ImportError: cannot import name 'Infomap' from 'infomap'.
But when I just type ‘python’ from the command line, and type 'from infomap import Infomap', it works fine, functions like 'add_link()' and 'run()' also work well. 
I doubt that it's a version problem, but it appears in both 1.0.0b50 and latest 1.3.0.
Looking forward to your reply. Thanks!

**Comment by danieledler** [comment]
Hi @zhangbw17!

First to check, you installed infomap with `pip install infomap` and don't have a local folder called 'infomap' next to the .py file?

Does `import infomap` work? And if so, what do you get from `dir(infomap)`?

When you start from command line and get the error, do you just type `python yourfile.py`? What operating system do you use?

**Comment by zhangbw17** [comment]
I can't believe I made such a silly mistake that I was careless while naming my py file 'infomap'. Thanks for your patience.

**Comment by danieledler** [comment]
No problem, glad you sorted it out, I have made the same mistake! 😄
