### ISSUE TITLE
python3 can't install and return some error

### ISSUE THREAD

**Issue by XiaoXiao2015** [mapequation/infomap#19]
Hi, I download this tools and can make successful, But when I enter examples/python, and make some error come out,Here is the error:
./infomap_wrap.cpp:2452: error: ‘PyCObject_Import’ was not declared in this scope
./infomap_wrap.cpp: In function ‘void SWIG_Python_SetModule(swig_module_info*)’:
./infomap_wrap.cpp:2521: error: ‘PyCObject_FromVoidPtr’ was not declared in this scope
./infomap_wrap.cpp:2512: warning: unused variable ‘swig_empty_runtime_method_table’
./infomap_wrap.cpp: In function ‘swig_type_info* SWIG_Python_TypeQuery(const char*)’:
./infomap_wrap.cpp:2544: error: ‘PyCObject_AsVoidPtr’ was not declared in this scope
./infomap_wrap.cpp:2549: error: ‘PyCObject_FromVoidPtr’ was not declared in this scope
./infomap_wrap.cpp: In function ‘std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >* std_vector_Sl_std_string_Sg____getitem____SWIG_0(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, PySliceObject*)’:
./infomap_wrap.cpp:4462: error: cannot convert ‘PySliceObject*’ to ‘PyObject*’ for argument ‘1’ to ‘int PySlice_GetIndices(PyObject*, Py_ssize_t, Py_ssize_t*, Py_ssize_t*, Py_ssize_t*)’
./infomap_wrap.cpp: In function ‘void std_vector_Sl_std_string_Sg____setitem____SWIG_0(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, PySliceObject*, const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’:
./infomap_wrap.cpp:4471: error: cannot convert ‘PySliceObject*’ to ‘PyObject*’ for argument ‘1’ to ‘int PySlice_GetIndices(PyObject*, Py_ssize_t, Py_ssize_t*, Py_ssize_t*, Py_ssize_t*)’
./infomap_wrap.cpp: In function ‘void std_vector_Sl_std_string_Sg____delitem____SWIG_1(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, PySliceObject*)’:
./infomap_wrap.cpp:4480: error: cannot convert ‘PySliceObject*’ to ‘PyObject*’ for argument ‘1’ to ‘int PySlice_GetIndices(PyObject*, Py_ssize_t, Py_ssize_t*, Py_ssize_t*, Py_ssize_t*)’
./infomap_wrap.cpp: In function ‘std::deque<unsigned int, std::allocator<unsigned int> >* std_deque_Sl_unsigned_SS_int_Sg____getitem____SWIG_0(std::deque<unsigned int, std::allocator<unsigned int> >*, PySliceObject*)’:
./infomap_wrap.cpp:5026: error: cannot convert ‘PySliceObject*’ to ‘PyObject*’ for argument ‘1’ to ‘int PySlice_GetIndices(PyObject*, Py_ssize_t, Py_ssize_t*, Py_ssize_t*, Py_ssize_t*)’
./infomap_wrap.cpp: In function ‘void std_deque_Sl_unsigned_SS_int_Sg____setitem____SWIG_0(std::deque<unsigned int, std::allocator<unsigned int> >*, PySliceObject*, const std::deque<unsigned int, std::allocator<unsigned int> >&)’:
./infomap_wrap.cpp:5035: error: cannot convert ‘PySliceObject*’ to ‘PyObject*’ for argument ‘1’ to ‘int PySlice_GetIndices(PyObject*, Py_ssize_t, Py_ssize_t*, Py_ssize_t*, Py_ssize_t*)’
./infomap_wrap.cpp: In function ‘void std_deque_Sl_unsigned_SS_int_Sg____delitem____SWIG_1(std::deque<unsigned int, std::allocator<unsigned int> >*, PySliceObject*)’:
./infomap_wrap.cpp:5044: error: cannot convert ‘PySliceObject*’ to ‘PyObject*’ for argument ‘1’ to ‘int PySlice_GetIndices(PyObject*, Py_ssize_t, Py_ssize_t*, Py_ssize_t*, Py_ssize_t*)’
error: command 'gcc' failed with exit status 1
make[1]: *** [python] Error 1
make[1]: Leaving directory `/usr/local/infomap'
My computer is centos, python version is 3.5.1, gcc 4.4.6, how to solve this problem?Thanks very much

**Comment by danieledler** [comment]
Hi, it seems you don't have [SWIG](http://www.mapequation.org/code.html#Examples-with-other-languages) installed?

If you have problems installing it, you may get help from this Dockerfile I recently used to compile the R examples with swig:

```
FROM rocker/rstudio

RUN apt-get update && apt-get install -y \
    build-essential \
    libpcre3-dev \
    autoconf \
    automake \
    libtool \
    bison \
    git \
    libboost-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/swig/swig/archive/rel-3.0.12.tar.gz \
&& tar -zxf rel-3.0.12.tar.gz \
&& cd swig-rel-3.0.12 \
&& rm -f ../rel-3.0.12.tar.gz \
&& ./autogen.sh \
&& ./configure \
&& make \
&& make install
```

**Comment by danieledler** [comment]
Hi, it is likely due to an old version of SWIG. I have not tested with version 1.3 or even 2.0, only the 3.0 release. Can you try install the latest version and tell me how it goes?

**Comment by xxkkrr** [comment]
I update the SWIG version to 3.0.12 and it works. I found that the infomap lib is added to the default python2 in CentOS and I use ananconda3 to run python3, so I can only use infomap in python2. Anyway, thanks a lot !

**Comment by danieledler** [comment]
It should work with python3 too, try `make python3`.

**Comment by xxkkrr** [comment]
It works with python3. Thanks for your help again.

**Comment by Kiteflyingee** [comment]
How do you solve this problem, I have recently encountered this problem, python2 works, but anaconda's python3 not work
