### ISSUE TITLE
generateMemoryNetworkWithInterLayerLinksFromData distributes memory links from interlinks as if multiplex network were directed

### ISSUE THREAD

**Issue by ulfaslak** [mapequation/infomap#2]
Given a network:

> *Vertices 3
> 0 "0"
> 1 "1"
> 2 "2"
> *Intra
> 0 0 1 1
> 0 1 2 1
> 1 0 2 1
> 1 1 2 1
> 2 0 1 1
> 2 0 2 1
> *Inter
> 0 0 2 0.5
> 1 0 2 0.5
> 0 1 1 0.5
> 0 1 2 0.5
> 0 2 1 0.5
> 1 2 2 0.5

Infomap seems to add memory links to the internal representation of the network, as if the links in the pajek format were directed. I'm running Infomap on the given network like:

`./Infomap threetriangles.net test_output/ -i multiplex -z --overlapping`

With output:

>=======================================================

>   Infomap v0.18.14 starts at [2016-10-26 19:46:09]
>   -> Input network: threetriangles.net
>   -> Output path:   test_output/
>   -> Configuration: input-format = multiplex
>                     overlapping
>                     zero-based-numbering
> -> Use undirected flow and 2nd order Markov dynamics
> /=======================================================
> Parsing multiplex network from file 'threetriangles.net'... done!
>  --> Found 6 intra-network links in 3 layers.
>  --> Found 6 inter-network links in 3 layers.
> Intra-network links on layer 1:  ==> 3 nodes and 2 links.
> Intra-network links on layer 2:  ==> 3 nodes and 2 links.
> Intra-network links on layer 3:  ==> 3 nodes and 2 links.
> Generating memory network with inter layer links from data... connecting layers... done!
>   -> Found 3 nodes and 11 memory links.
>   -> Generated 9 memory nodes and 11 memory links.
> Printing network to test_output/threetriangles.net... done!
> Calculating global flow...
>   -> Using undirected links.
> Calculating one-level codelength... done!
>   -> One-level codelength: 3.098929564
> 
> Attempt 1/1 at [2016-10-26 19:46:09]
> Initiated to codelength 3.09893 + 2 = 5.098929564 in 9 modules.
> Two-level compression: 49% to 1 modules with codelength 1.584962501
> 
> Building output tree... merging 9 memory nodes within 1 modules... to 3 nodes... writing .tree... done!
> 
> 
> Best end modular solution in 2 levels:
> Per level number of modules:         [          1,           0] (sum: 1)
> Per level number of leaf nodes:      [          0,           9] (sum: 9)
> Per level average child degree:      [          1,           9] (average: 8.2)
> Per level codelength for modules:    [-0.000000000, 0.000000000] (sum: -0.000000000)
> Per level codelength for leaf nodes: [0.000000000, 1.584962501] (sum: 1.584962501)
> Per level codelength total:          [-0.000000000, 1.584962501] (sum: 1.584962501)
> 
> /===================================================
>   Infomap ends at [2016-10-26 19:46:09]
>   (Elapsed time: 0s)
> /===================================================

As seen from the output Infomap creates 11 memory links, corresponding to the 6 Intra-layer links plus 5 Inter-to-Intra links (5 because that's how many there can be drawn if Intra-layer edges are directed).

For this network Infomap should create 6 [Intra] + 18 [Inter/Intra] memory edges. Here's a figure that shows the example network with all memory edges. Black is *Intra, grey is *Inter and {red, green, blue} are interlayer memory links as I believe they should be generated in Infomap.

[A_test.pdf](https://github.com/mapequation/infomap/files/554529/A_test.pdf)

In the code it all goes right until line 311 - 313 of MultiplexNetwork.cpp where a LinkMap is extracted as if the network is directed. 

```
const LinkMap& otherLayerLinks = m_networks[layer2].linkMap();
// Distribute inter-link to the outgoing intra-links of the node in the inter-linked layer
LinkMap::const_iterator otherLayerOutLinkIt = otherLayerLinks.find(nodeIndex);
```

I'm not very sharp on C++ so I couldn't figure out how to fix that, and extract a LinkMap that includes all neighbors of nodeIndex in layer2, but I think doing that would solve the problem.

**Comment by mrosvall** [comment]
You are right. The multiplex format builds on the memory network representation, which typically operates on inherently directed pathway data.

We need to either make explicit that the multiplex format assumes directed links (and not output to terminal "Use undirected flow and...") or treat them as undirected by default.

**Comment by ulfaslak** [comment]
Is it possible to make it such that the user can just use the -d and -u flags to control whether the multiplex network is parsed as directed or undirected? And then if a multiplex network is parsed as directed, interlayer links under *Inter are still parsed as undirected because: why should a relax step be directed?

**Comment by mrosvall** [comment]
9153db3 and 73ed620 fix this problem. Now all links are interpreted as undirected, though they are converted to directed links between state nodes in the internal representation. http://www.mapequation.org/code.html#Multiplex-format should be updated to clarify this.
