### ISSUE TITLE
confused about interpreting cluster labels, tree file doesn't match get_modules

### ISSUE THREAD

**Issue by jamestwebber** [mapequation/infomap#225]
Hello there! Big fan of infomap (was instrumental to my thesis, way back when) and I'm happy to see python bindings available.

I've been puzzling over the cluster assignments. It seems like the `tree` file does not have the same module labels as the `get_module` method. Furthermore, the `get_module` method seems to be happy to provide labels at every level, even though some nodes only have a depth of one or two levels.

I didn't see documentation about this, is there a mapping between these two labelings? How would I extract the tree-file labeling from the python object?

**Comment by antoneri** [comment]
Hi, and thanks for reaching out!

I'm on summer holiday (maybe @danieledler can chime in), but in short:

This is a [known issue](https://github.com/mapequation/infomap/issues/221) but has not been released yet.

I will get back to you in a couple of weeks!

**Comment by danieledler** [comment]
Hi, just adding quickly that the difference between the `.tree` file labelling (which can be accessed via the `path` property in the iterator) and the `.clu` file labelling (accessed via `get_module`) is that the module ids in any level in the latter are global whereas the numbers on any level in the tree path are local, relative to its parent.

The global property is also why `get_module` would always return a value even when there are no modules at the specified level for some nodes, it will then reflect the deepest module structure available.

**Comment by antoneri** [comment]
To answer your original question: The tree-file labeling is available through `node.path`.

I'll close this issue, for now, please re-open it if you have further questions!
