### ISSUE TITLE
addLink function missing from Infomap

### ISSUE THREAD

**Issue by poldrack** [mapequation/infomap#25]
hi - I am trying to use the pip installed version of the python package, but the code from the jupyter notebook doesn't seem to work. First, the initial import fails:

```
In [6]: from infomap import infomap
   ...:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-0c8597e1552c> in <module>()
----> 1 from infomap import infomap

ImportError: cannot import name 'infomap'

```

However, it works with ```from infomap import Infomap```

The bigger problem is that the addLink function seems to be missing from Infomap:

```
In [7]: infomapWrapper = infomap.Infomap("--two-level")
   ...:
   ...: # Add link weight as an optional third argument
   ...: infomapWrapper.addLink(0, 1)
   ...:
   ...:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-3febb79f95d2> in <module>()
      2
      3 # Add link weight as an optional third argument
----> 4 infomapWrapper.addLink(0, 1)

~/anaconda3/envs/py3/lib/python3.6/site-packages/infomap.py in <lambda>(self, name)
   2834     for _s in [InfomapBase]:
   2835         __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
-> 2836     __getattr__ = lambda self, name: _swig_getattr(self, Infomap, name)
   2837     __repr__ = _swig_repr
   2838

~/anaconda3/envs/py3/lib/python3.6/site-packages/infomap.py in _swig_getattr(self, class_type, name)
     78     if method:
     79         return method(self)
---> 80     raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
     81
     82

AttributeError: 'Infomap' object has no attribute 'addLink'
```

This is also evident from a listing of the object attributes. Has the API changed for the wrapper?

**Comment by danieledler** [comment]
Thanks for the feedback, the examples in the `examples/python` folder of the Infomap repo doesn't rely on installing Infomap from pip but on importing it from the locally built infomap package folder (by running `make` in the same folder).

The pip installed version is on the `v1-beta` branch, so checkout that for updated examples. You may have to remove the local infomap folder and just use `import infomap` to use the pip version.

This will probably change soon, as it is a bit confusing now. We are starting to build up the v1 documentation here: https://mapequation.github.io/infomap/

**Comment by ggautreau** [comment]
I have the same problem as @poldrack 

The addLink function is missing from Infomap even if I replace `from infomap import infomap` by `import infomap`

I installed infomap using pip, my version is '1.0.0-beta.15'

**Comment by dharif23** [comment]
I struggled with the infomap also. I would suggest you take a look at this code (Copied from infomap website)
```Python
import infomap

# Command line flags can be added as a string to Infomap
infomapSimple = infomap.Infomap("--two-level --directed")

# Access the default network to add links programmatically
network = myInfomap.network()

# Add weight as optional third argument
network.addLink(0, 1)
network.addLink(0, 2)
network.addLink(0, 3)
network.addLink(1, 0)
network.addLink(1, 2)
network.addLink(2, 1)
network.addLink(2, 0)
network.addLink(3, 0)
network.addLink(3, 4)
network.addLink(3, 5)
network.addLink(4, 3)
network.addLink(4, 5)
network.addLink(5, 4)
network.addLink(5, 3)

# Run the Infomap search algorithm to find optimal modules
myInfomap.run()

print("Found {} modules with codelength: {}".format(myInfomap.numTopModules(), myInfomap.codelength()))

print("Result")
print("\n#node module")
for node in myInfomap.iterTree():
  if node.isLeaf():
    print("{} {}".format(node.physicalId, node.moduleIndex()))
```
Although I tried to use `pip` installed version and also tried `v1-beta`. I found that there are a significant number of features are not working as it should so I reverted back to local import of C++ and Swig version.
Hope this helps.

**Comment by ggautreau** [comment]
Ok thank you ! Now it works for me but I think there is a little error in your example @dharif23 as well as in the example here: https://mapequation.github.io/infomap/

The variable `infomapSimple`  of the line code 4 is then called `myInfomap` in the next lines...

**Comment by dharif23** [comment]
@ggautreau I noticed that too. But I think it's an understandable mistake that can be overlook for now as this is in beta or an new issue can be opened to fix this little issue.
