### ISSUE TITLE
Entropy correction

### ISSUE THREAD

**Issue by danieledler** [mapequation/infomap#257]
Correct for negative entropy bias in small samples (many modules).

**Comment by astruck** [comment]
Hello, 
where could I read up on this feature? Why was it necessary and what means "small samples"?
Thank you very  much!
--Alexander

**Comment by danieledler** [comment]
Hi @astruck, thanks for your interest in Infomap!

It is currently an undocumented feature but it basically corrects for an underestimated codelength in _incomplete_ or _under-sampled_ networks, where the bias according to a simple Miller estimator turns out to increase proportional to the number of modules and inversely proportional to the number of observations making up the link weights. Small samples here basically means high ratio of number of modules to the total link weight.

**Background:**
It's a well-known problem with non-trivial solutions that the entropy is underestimated for small samples if we use the observed frequencies instead of the true probabilities and that we need to correct for this for a good estimation of true entropy. See https://www.nowozin.net/sebastian/blog/estimating-discrete-entropy-part-1.html for more info on that.

It is easy to understand this effect from a multinomial distribution with $n$ samples over $k$ events and uniform probabilities. Uniform probabilities maximises the entropy to $\log_2 k$, but the empirical frequencies only approaches a uniform distribution with increasing sample size and thus underestimates the true entropy.
