### ISSUE TITLE
install issue on ubuntu

### ISSUE THREAD

**Issue by GlennCGL** [mapequation/infomap#276]
gcc: error：unrecognized command line option ‘-std=c++14’
  error: command 'gcc' failed with exit status 1
=======================
python 3.7, when I try to install Infomap on Ubuntu, it got the error message above.
how to solve it.

**Comment by GlennCGL** [comment]
gcc version: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

**Comment by GlennCGL** [comment]
I notice that 'Installing on other operating systems requires a working gcc or clang compiler.'.
May I ask what are the steps in details?

**Comment by GlennCGL** [comment]
By the way, I can not upgrade my gcc version. How can I pip install Infomap successfully?

**Comment by antoneri** [comment]
Hi and thanks for reaching out!

Unfortunately, Infomap requires a C++14 compatible compiler even if you install the Python version. This means probably at least GCC version 5.

There's also [pre-built binaries](https://www.mapequation.org/infomap/#DownloadBinary) available for download, but I suspect that if you cannot upgrade GCC, you also can't install the needed libraries. Those binaries won't get you access to the Python API though.

If you cannot upgrade GCC, you can run Infomap in a [Docker container](https://hub.docker.com/r/mapequation/infomap).

I'm afraid these are your options, hope this helps!
