### ISSUE TITLE
Bipartite mode seems to include 'bipartite nodes' by default.

### ISSUE THREAD

**Issue by rodrigolece** [mapequation/infomap#30]
The documentation for the option `--show-bipartite-nodes`  says "Include the bipartite nodes in the output." This obviously makes me think that the default option is not to include the bipartite nodes (the option that I would like), but even without this option  the `.tree` file includes them. 

I'm using version 0.19.25 and Python 2. Unfortunately I'm working on a server without admin privileges, so I I don't know how it was intalled. My guess though is a .zip file because there it's not a git repo.

**Comment by danieledler** [comment]
The options are updated on http://www.mapequation.org/code.html now, thanks!

Regarding the documentation for bipartite networks using Python there is a basic example in `examples/python/example-bipartite.py` in the master branch that you can check out, but it's not available in the v1-beta branch yet (the version on pip). We will have that soon though, and then we will also add it to and expand the documentation on https://mapequation.github.io/infomap/.
