### ISSUE TITLE
Bipartite mode: not clear in the documentation what algorithm is used.

### ISSUE THREAD

**Issue by rodrigolece** [mapequation/infomap#31]
In the paper *Efficient community detection of network flows for varying Markov times and bipartite networks* there are three algorithms described for a bipartite network, but it's not clear from the documentation which one is Infomap using.

My guess is that the fast approximation is used. If that's the case, can I run Infomap in normal mode with a Markov time of 2 and get the bipartite results?

**Comment by antoneri** [comment]
I will close this issue as it's been stale for so long.

We have updated the documentation at https://www.mapequation.org/infomap/#InputBipartite
Please see if it answers your questions!
