### ISSUE TITLE
install infomap on win10, error: c++14.0 required

### ISSUE THREAD

**Issue by Yifeng007duan** [mapequation/infomap#33]
hi,  I have tried several ways to install infomap, but failed,says the c++14.0 is required, so i install vc17 and Visual C++ Build Tools, still failed

1. follow the tutor on this web, i use "pip install infomap" in my dos window

2. next, i download the infomap-1.0.0b3.tar.gz on pypi, still couldn't work, it says:
    
error: command 'cl.exe' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for infomap
  error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-l8fj6rgp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-3snnngrg\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-l8fj6rgp\

![2018-10-16_203356](https://user-images.githubusercontent.com/37182840/47016694-06cfc200-d183-11e8-88ee-b6e307bfb1fe.png)

**Comment by reihaneab** [comment]
@Yifeng007duan Did you solve the problem?

**Comment by danieledler** [comment]
Sorry I missed this, there are two options described [here](https://stackoverflow.com/a/41724634) to solve the issue with `cl.exe`. Have you tried those?

**Comment by danieledler** [comment]
Closing now as the issue may be old, but please re-open if it's still an issue. In that case, I would recommend first upgrading/reinstalling Anaconda to get the build tools in path, and then try `pip install --upgrade infomap`.
