### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by pojeda** [mapequation/infomap#346]
Hi, 

How do you test if code implementation is giving correct results? Do you have some unit tests or a way to validate the Infomap code?

/Pedro

**Comment by danieledler** [comment]
Hi Pedro,

On the [python api](https://github.com/mapequation/infomap/blob/master/interfaces/python/infomap.py) we use [doctest](https://docs.python.org/3/library/doctest.html) that runs automatically with Github actions on new commits and should cover the common cases. We also have a few additional tests in a test folder that can be run manually, but certainly the test coverage can be improved.
