### ISSUE TITLE
How to show overlapping result?

### ISSUE THREAD

**Issue by GaoFangshu** [mapequation/infomap#35]
Take the network in the paper as an example:
![img](https://user-images.githubusercontent.com/11488742/47846599-6a085800-de03-11e8-9626-d932203862d4.png)
and make it to link txt file:
[overlap_test.txt](https://github.com/mapequation/infomap/files/2538091/overlap_test.txt)

I ran the infomap with and without flag `--overlapping`, but the results were same. Is there a way to show overlapping?

Here is my code:
```python
infomapWrapper = infomap.Infomap()
network = infomapWrapper.network()
network.readInputData("data/overlap_test.txt")
infomapWrapper.run()
for node in infomapWrapper.iterTree():
    print(node.path(), node.moduleIndex(), node.physicalId)
"""
Result:
() 0 0
(0,) 0 0
(0, 0) 0 1
(0, 1) 0 2
(0, 2) 0 3
(0, 3) 0 4
(1,) 1 0
(1, 0) 1 5
(1, 1) 1 6
(1, 2) 1 7
(1, 3) 1 8
(1, 4) 1 9
"""

infomapWrapper_o = infomap.Infomap("--overlapping")
network_o = infomapWrapper_o.network()
network_o.readInputData("data/overlap_test.txt")
infomapWrapper_o.run()
for node in infomapWrapper_o.iterTree():
    print(node.path(), node.moduleIndex(), node.physicalId)
"""
Result:
() 0 0
(0,) 0 0
(0, 0) 0 1
(0, 1) 0 2
(0, 2) 0 3
(0, 3) 0 4
(1,) 1 0
(1, 0) 1 5
(1, 1) 1 6
(1, 2) 1 7
(1, 3) 1 8
(1, 4) 1 9
"""
```

**Comment by antoneri** [comment]
The `--overlapping` flag has been removed unfortunately. Overlapping detection is still available for higher-order networks.
