### ISSUE TITLE
make python install

### ISSUE THREAD

**Issue by wolfiex** [mapequation/infomap#37]
When running `make python` on the systems outlined below I get the following errors. 

Ubuntu:
`    src/core/FlowData.h:78: Error: Syntax error in input(3).`

OpenSuse:
```
A set of warnings ... + 

File "setup.py", line 8, in <module>
from pkg_resources import parse_version
ImportError: No module named 'pkg_resources'
Makefile:134: recipe for target 'python' failed
make: *** [python] Error 1
```

**Comment by wolfiex** [comment]
Installing with pip gives the following on the simple examples:

```
Traceback (most recent call last):
  File "z_multilayer_infomap.py", line 59, in <module>
    for node in myInfomap.iterTree():
TypeError: 'NoneType' object is not callable
```

**Comment by danieledler** [comment]
Hi, sorry for missing this. For the first error, have you tried [this](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources/10538412#10538412)?

On the second error, pip is using the `v1-beta` branch, so you have to checkout that for the examples to be updated to work with that version.
