### ISSUE TITLE
Multilayer networks missing in 1.0 beta?

### ISSUE THREAD

**Issue by poplarShift** [mapequation/infomap#39]
First, thanks for all the great material on your work!

Am I correct that multilayer network analysis is still missing from the 1.0 beta? Any idea when that will be added?

Second, when I run a multilayer network, I can't seem to find the option that prints layer-wise or overlapping communities (if that makes any sense).

**Comment by danieledler** [comment]
Hi, v1-beta supports multilayer networks too, there is a basic example in `examples/python/multilayer.py` in that branch.

In that, we print `"{node.layerId} {node.physicalId} {node.moduleIndex()}"` for each node, which now is a state node with a layer id and physical node id. From there you should be able to collect your clusters layer-wise and see how they overlap.

Please tell me if you don't get it to work!

**Comment by poplarShift** [comment]
Thanks, will test that out!
