### ISSUE TITLE
inter and intra link don't work for multilayer network for python

### ISSUE THREAD

**Issue by LaZzyMan** [mapequation/infomap#48]
I'm using the v1.0 beta version in my project. According to the introduce [here](http://www.mapequation.org/code.html#Multiplex-format), the "inter and intra" can be my best choice and I found the methods in the Network class:
```
def addMultilayerLink(self, layer1, n1, layer2, n2, weight):
    return _infomap.Network_addMultilayerLink(self, layer1, n1, layer2, n2, weight)
def addMultilayerIntraLink(self, layer, n1, n2, weight):
    return _infomap.Network_addMultilayerIntraLink(self, layer, n1, n2, weight)
```

But when I used it in my code like this:
```
infomap_wrapper = infomap.Infomap('--two-level --directed --expanded')
network = infomap_wrapper.network()
network.addMultilayerIntraLink(layer_0, node_0, node_1, weight)
...
infomap_wrapper.run()
```

There is an error:
```
File "/Users/zz/anaconda3/lib/python3.7/site-packages/infomap.py", line 2635, in run
    return _infomap.InfomapBase_run(self, *args)
RuntimeError: No input file to read network
```
it seems that the network was not read by the run() method.

Then I changed my code like this:
```
infomap_wrapper = infomap.Infomap('--two-level --directed --expanded')
infomap_wrapper = infomap_wrapper.network()
infomap_wrapper.addMultilayerIntraLink(layer_0, node_0, node_1, weight)
...
infomap_wrapper.run()
```

There was an error again:
```
File "/Users/zz/anaconda3/lib/python3.7/site-packages/infomap.py", line 3306, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Infomap, name)
  File "/Users/zz/anaconda3/lib/python3.7/site-packages/infomap.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Infomap' object has no attribute 'addMultilayerInterLink'
```
So how can I fix it without using the command method?

**Comment by wweir827** [comment]
I had the same error trying to run on multilayer network.  it looks as though if you add the line 

`infomap_wrapper.network.generateStateNetworkFromMultilayerWithInterLinks()
`
after adding in the links it seems to work. 

`infomapSimple = infomap.Infomap("--two-level")

net=infomapSimple.network()

net.addMultilayerIntraLink(1, 1, 2, 1.0)
net.addMultilayerIntraLink(1, 2, 3, 1.0)
net.addMultilayerIntraLink(2, 1, 3, 1.0)
net.addMultilayerIntraLink(2, 2, 3, 1.0)

net.addMultilayerInterLink(1, 1, 2, 1.0)
net.addMultilayerInterLink(1, 2, 2, 1.0)
net.addMultilayerInterLink(1, 3, 2, 1.0)
net.generateStateNetworkFromMultilayerWithInterLinks()

infomapSimple.run()


print("Found {} modules with codelength: {}".format(infomapSimple.numTopModules(), infomapSimple.codelength()))

print("Result")
print("\n#node module")
for node in infomapSimple.iterTree():
    if node.isLeaf():
        print("{} {}".format(node.physicalId, node.moduleIndex()))
`

Output: 
Found 1 modules with codelength: 1.5545851693377997
Result

#node module
1 0
2 0
3 0
1 0
3 0
2 0
