### ISSUE TITLE
undefined symbol in python bindings

### ISSUE THREAD

**Issue by rossgriebenow** [mapequation/infomap#49]
I installed in the Windows 10 Bash shell as suggested in the installation instructions, and I am able to run the c++ examples, but when I try to run the python examples or import the module I get this error:
`ross@Ross-laptop:~/infomap/examples/python$ python example-simple.py
Traceback (most recent call last):
  File "example-simple.py", line 1, in <module>
    from infomap import infomap
  File "/home/ross/infomap/examples/python/infomap/infomap.py", line 13, in <module>
    from . import _infomap
ImportError: /home/ross/infomap/examples/python/infomap/_infomap.so: undefined symbol: InfomapAddLink`

I didn't notice any errors when building the python bindings, could you advise?
Thanks!

**Comment by wolfiex** [comment]
Confirmed error on 
`...python3.7/site-packages/_infomap.cpython-37m-x86_64-linux-gnu.so: undefined symbol: InfomapAddLink` 

It occurs on the import statement

**Comment by bojone** [comment]
I met the same problem in v0.x
