### ISSUE TITLE
Trials for clustering

### ISSUE THREAD

**Issue by zhaotao1987** [mapequation/infomap#50]
Hi, 

I just started to use this stand-alone infomap package, thank you very much, it is much faster. Previously I used the one implemented in igraph.  I just clustered a network with >3 million nodes and >84 million edges in about one hour, using the following command:
`Infomap  input_network output_folder  --clu -N 10 --map -2`

Here's a result of clustering process:
```Finished clustering 'MergedBlocks_2cols.sim' in 10 trials with:
Iteration                 Seconds          Modules       Perplexity         maxDepth    weightedDepth       Codelength
1                   524.860000000           179442  10550.366034729                2      2.000000000      7.758878748 *
2                   535.210000000           179517  10549.729204022                2      2.000000000      7.758735274 *
3                   500.330000000           179532  10554.847902507                2      2.000000000      7.759256961
4                   499.660000000           179515  10554.435378556                2      2.000000000      7.759153349
5                   441.620000000           179433  10544.960890735                2      2.000000000      7.759558923
6                   408.520000000           179500  10551.325096902                2      2.000000000      7.758993814
7                   391.420000000           179519  10541.564614132                2      2.000000000      7.759484420
8                   408.880000000           179520  10556.153246348                2      2.000000000      7.758981082
9                   385.460000000           179539  10553.808348660                2      2.000000000      7.758741310
10                  410.980000000           179474  10553.866272342                2      2.000000000      7.758730719 *
----------------------------------------------------------------------------------------------------------------------
Min:                385.460000000           179433  10541.564614132                2      2.000000000      7.758730719
Median:             441.620000000           179517  10553.808348660                2      2.000000000      7.758993814
Average:            450.694000000           179499  10551.105698893      2.000000000      2.000000000      7.759051460
Max:                535.210000000           179539  10556.153246348                2      2.000000000      7.759558923


Best end modular solution in 2 levels:
Per level number of modules:         [     179474,           0] (sum: 179474)
Per level number of leaf nodes:      [          0,     3045854] (sum: 3045854)
Per level average child degree:      [     179474,      16.971] (average: 10002.892070789)
Per level codelength for modules:    [0.216598906, 0.000000000] (sum: 0.216598906)
Per level codelength for leaf nodes: [0.000000000, 7.542131813] (sum: 7.542131813)
Per level codelength total:          [0.216598906, 7.542131813] (sum: 7.758730720)

===================================================
  Infomap ends at [2019-05-17 00:00:06]
  Elapsed time: 1h 11m 12s (5156.620000000s)
===================================================
```
However I am not so familiar with all these parameters. Although It picked the best trial with the lowest codelength (10th trial), for me the results from each trial doesn't differ that much. How necessary it is to use multiple trials, do I have to set it even higher, or sometimes even one trial is already enough. 

Thank you very much! 
Best, Tao

**Comment by danieledler** [comment]
Hi,

Nice to hear about the improvements compared to the old igraph implementation! As you noticed, the codelengths don't differ much in this case, but in general it's hard to know beforehand as it depends on the complexity of the solution landscape, but a few trials may be good to check that out.

If there is a clear community structure within the network, one run would likely be enough to find a close to optimal solution, as there are multiple steps of fine-tuning and coarse-tuning within one run after the initial stochastic greedy agglomerative steps.

It may also be the case that there are similarly high local optima far from each other in the solution landscape, so a similar codelength doesn't necessarily mean that the solutions are similar. In a future version, we will have a feature to automatically detect that, but for now, you may inspect the solutions from all trials by adding `--print-all-trials`.

Does it answer your questions?

**Comment by zhaotao1987** [comment]
> Hi,
> 
> Nice to hear about the improvements compared to the old igraph implementation! As you noticed, the codelengths don't differ much in this case, but in general it's hard to know beforehand as it depends on the complexity of the solution landscape, but a few trials may be good to check that out.
> 
> If there is a clear community structure within the network, one run would likely be enough to find a close to optimal solution, as there are multiple steps of fine-tuning and coarse-tuning within one run after the initial stochastic greedy agglomerative steps.
> 
> It may also be the case that there are similarly high local optima far from each other in the solution landscape, so a similar codelength doesn't necessarily mean that the solutions are similar. In a future version, we will have a feature to automatically detect that, but for now, you may inspect the solutions from all trials by adding `--print-all-trials`.
> 
> Does it answer your questions?

Hi Daniel,

Yes, thank you so much for the nice answer. Excellent.

Best, Tao

**Comment by mrosvall** [comment]
Here is a new pre-print that provides a robust method to determine when to safely stop iterating stochastic search algorithms: https://arxiv.org/abs/1905.11230
