### ISSUE TITLE
infomap weighted clustering too greedy

### ISSUE THREAD

**Issue by zhaotao1987** [mapequation/infomap#51]
Hi,

Thanks for the help last time, this time I tried weighted clustering to the same network.  It worked nicely. Here I have some new questions:  the following figure is one example from my data.  Edge weights were indicated by color, the redder, the higher. 

Unweighted clustering returned cluster1 and cluster2. Weighted clustering clustered cluster1 and 2A together, cluster2B another one. Just because there is one edge with a higher score connecting them. 
However in such cases, I think it would be better not to cluster together (cluster 1 and 2A).
So I wonder if it is possible to consider edge weight and edge connections at the same time. Are there some related parameters I could tweak ?

Also another question: For weighted clustering, is it crucial to normalize the weight scores first, or the algorithm will do some kind of normalization itself, does that influence much? 

Thank you very much.

Best, Tao
![image](https://user-images.githubusercontent.com/16197676/58264277-dfc31980-7d7d-11e9-985f-c43e5ab26891.png)

**Comment by danieledler** [comment]
Sorry I have missed to answer this @zhaotao1987 , but if it is still relevant:

1. The result looks strange when plotted with equally wide links, but if the single link were for example ten times as wide as the ones within the clusters, like a highway with commuters between two cities, it may no longer look strange. Is this your case? If not, please share your network and I can take a look. That it is just a single link doesn't matter for weighted networks, it's the flow that counts. If you want a hybrid solution between unweighted and weighted, I guess the simplest thing is to re-weight the links to decrease the relative difference. Maybe it makes sense to use a log scale?

2. It doesn't matter if you normalize edge weights if you do it with globally, i.e. multiplying each link weight with the same constant. Infomap will translate the weights to flow (visit frequencies of a random walker) which sums up to 1. For undirected networks, the flow an a link with weight w_i is simply w_i / sum(w_i). For directed networks, the flow is calculated with the PageRank algorithm, which generally breaks the simple connection between weight and flow, but if your weights can already be interpreted as flow, like the number of cars per time unit on a road, you may skip this step by using `-f rawdir`.
