### ISSUE TITLE
pip installation on Windows

### ISSUE THREAD

**Issue by svrijenhoek** [mapequation/infomap#53]
Hi,

Currently trying to pip install on a Windows system, but I get the following error:

Building wheel for infomap (setup.py) ... error
  ERROR: Complete output from command 'c:\users\sanne\anaconda3\envs\dart\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Sanne\\AppData\\Local\\Temp\\pip-install-laamelzr\\infomap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Sanne\AppData\Local\Temp\pip-wheel-8td12f0_' --python-tag cp36:
  ERROR: c:\users\sanne\anaconda3\envs\dart\lib\site-packages\setuptools\dist.py:472: UserWarning: Normalizing '1.0.0-beta.50' to '1.0.0b50'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  copying infomap.py -> build\lib.win-amd64-3.6
  running egg_info
  writing infomap.egg-info\PKG-INFO
  writing dependency_links to infomap.egg-info\dependency_links.txt
  writing entry points to infomap.egg-info\entry_points.txt
  writing top-level names to infomap.egg-info\top_level.txt
  reading manifest file 'infomap.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'infomap.egg-info\SOURCES.txt'
  running build_ext
  building '_infomap' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\src
  creating build\temp.win-amd64-3.6\Release\src\core
  creating build\temp.win-amd64-3.6\Release\src\io
  creating build\temp.win-amd64-3.6\Release\src\utils
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -Ic:\users\sanne\anaconda3\envs\dart\include -Ic:\users\sanne\anaconda3\envs\dart\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /Tp.\infomap_wrap.cpp /Fobuild\temp.win-amd64-3.6\Release\.\infomap_wrap.obj -DAS_LIB -DPYTHON -Wno-deprecated-register -std=c++14
  **cl : Command line error D8021 : invalid numeric argument '/Wno-deprecated-register'**
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ERROR: Failed building wheel for infomap

Any help would be very much appreciated. Running Python 3.6, latest buildtools (should be) installed

**Comment by Castel18** [comment]
Do you have found a solution? I have the same problem.

**Comment by Niko-shvets** [comment]
Hi, I have the same problem, did you found solution?

**Comment by mrosvall** [comment]
Thanks for letting us know about the problem. We are looking for a solution.

**Comment by danieledler** [comment]
I just want to let you know that I'm working on a solution. I got past the problem above but ended up in another os specific issue.

**Comment by danieledler** [comment]
Hi, finally I got it to work on our Windows computer, after some changes in the Infomap code together with some updates on the Windows computer (installing anaconda). Can you please try again now, with `pip install --upgrade infomap` and see if you get it to work? Check that you get version `1.0.0b54`.

I will probably try to upload a binary distribution soon so that the pip installation should work even without any recent c++ toolchain installed, which may still be an issue now.

**Comment by chocoelho** [comment]
`1.0.0b54` worked for me, thanks!
