### ISSUE TITLE
no module _infomap

### ISSUE THREAD

**Issue by jccazes** [mapequation/infomap#54]
Hello, 
after compiling by running Make in the Examples/python folder , 
i get the following error in jupyter notebook 

ModuleNotFoundError: No module named '_infomap'

and when i try to execute one of the example:  python3 example-bipartite.py 
i get a core dump error (segmentation) 
what is happening and how to fix it?

thank you

**Comment by xRadne** [comment]
I have the same issue. 

### Error
When using `pip install infomap`, I get a long error message ending with "ERROR: Failed building wheel for infomap"
I have tried it both on Windows using anaconda and Windows Subsystem for Linux. Same error. 

I have a basic knowledge of python, but no prior knowledge of c++.
What are the steps to install the package as a python module?

**Comment by antoneri** [comment]
The python examples are written for the newest version of the Infomap pip package. Only in rare cases should you need to build it yourself.

Try to upgrade the package with `pip install --upgrade infomap`.
