### ISSUE TITLE
input graph : is it possible to support string node names? 

### ISSUE THREAD

**Issue by zhaotao1987** [mapequation/infomap#56]
Hi,

It seems to me the program doesn't support node name as strings? My network has gene names as node names. It's just a huge network, and difficult (intense work ) for me to convert these nodes into integers, and later transfer back to original names.
``` -i<s> --input-format <s>                          Specify input format ('pajek', 'link-list', 'states', '3gram', 'multilayer' or 'bipartite') to override format possibly implied by file extension.```

Thank you very much.

Best, Tao

**Comment by antoneri** [comment]
Hi and thanks for submitting the issue.
Can you give an example from the data?

**Comment by antoneri** [comment]
Which version are you using (check with `infomap -v`)?

**Comment by antoneri** [comment]
Hi and thanks for your question!

We don't plan to support this feature directly, but we have discussed about including it in a helper program.
