### ISSUE TITLE
AttributeError: 'Infomap' object has no attribute 'tree'

### ISSUE THREAD

**Issue by Niko-shvets** [mapequation/infomap#59]
Hi, I am trying to use pip instaled infomap in Google colab and I found such problems:

```
from infomap import infomap

ImportError                               Traceback (most recent call last)
<ipython-input-68-0c8597e1552c> in <module>()
----> 1 from infomap import infomap

ImportError: cannot import name 'infomap'
```
But, yes I can just import infomap, but when I start work with finding Communites I have another problem

```
AttributeError                            Traceback (most recent call last)
<ipython-input-62-8ec325411ac0> in <module>()
----> 1 findCommunities(Graph)

<ipython-input-44-6521ecc83305> in findCommunities(G)
     13     infomapWrapper.run();
     14 
---> 15     tree = infomapWrapper.tree
     16 
     17     print("Found %d modules with codelength: %f" % (tree.numTopModules(), tree.codelength()))

AttributeError: 'Infomap' object has no attribute 'tree'
```

also problems with

```
AttributeError: 'Infomap' object has no attribute 'leafIter'
```

**Comment by chaosles** [comment]
I had the same problem :
`AttributeError: 'Infomap' object has no attribute 'tree'`
and
`AttributeError: 'Infomap' object has no attribute 'MemInfomap` 
in jupyter notebook.
It bothered me for a long time

**Comment by danieledler** [comment]
The python code you are using is for the old 0.x branch but the Infomap in pip is from the `v1-beta` branch. We will soon try to replace the master branch and update the documentation page to make this more clear, but you can see updated python example code in the v1-beta branch, or check https://mapequation.github.io/infomap/.

Sorry for the confusion!

**Comment by Niko-shvets** [comment]
Hi! Thank you for your respoce! I check example from v1-beta, but there you also use tree atribute, and I have the same error. I litlle bit confused.
code what I use
``
infomapWrapper = infomap.Infomap("--two-level --silent")

print("Building Infomap network from a NetworkX graph...")
for e in G.edges():
    infomapWrapper.addLink(*e)

print("Find communities with Infomap...")
infomapWrapper.run();

tree = infomapWrapper.tree

print("Found %d modules with codelength: %f" % (tree.numTopModules(), tree.codelength()))``
``

Also I tried fixed it without tree atribbute like this:
``
def findCommunities(G):
    """
    Partition network with the Infomap algorithm.
    Annotates nodes with 'community' id and return number of communities found.
    """
    infomapWrapper = infomap.Infomap("--two-level --silent")

    print("Building Infomap network from a NetworkX graph...")
    for e in G.edges():
        infomapWrapper.addLink(*e)

    print("Find communities with Infomap...")
    infomapWrapper.run();

    #tree = infomapWrapper.iterTree()

    print("Found %d modules with codelength: %f" % (infomapWrapper.numTopModules(), infomapWrapper.codelength()))

    communities = {}
    for node in infomapWrapper.iterLeafModules():
        communities[node.index] = node.moduleIndex()
    bb = nx.betweenness_centrality(G)
    isinstance(bb, dict)
    True
    print(nx.set_node_attributes(G, bb, 'communities'))
    return infomapWrapper.numTopModules(),communities
``
Can you help me?

**Comment by danieledler** [comment]
If you have checked out the `v1-beta` branch, the `.py` files in the `examples/python` folder should be updated to not use the old `.tree` syntax. Check for example `simple.py` for three ways of accessing the modules after the run:

```py
print("\n#node module")
for node,module in myInfomap.getModules().items():
	print(f"{node} {module}")


print("\n#path flow node module:")
for node in myInfomap.iterLeafNodes():
	print(node.path(), node.data.flow, node.id, node.moduleIndex())

print("\nPrinting tree to output/test.tree...")
myInfomap.writeTree('output/test.tree')
```

I noticed though that the jupyter notebook in that folder is still the old one, so maybe you checked that one? In that case, you can check [this one](https://github.com/mapequation/infomap-notebooks/blob/master/1_1_infomap_intro.ipynb) instead.
