### ISSUE TITLE
AttributeError: module 'infomap' has no attribute 'Infomap'  in v1-beta Branch of Infomap

### ISSUE THREAD

**Issue by dhanbr** [mapequation/infomap#62]
I have recently used infomap v1-beta Branch. After compiling the simple.py store n the examples/python directory, I have got the following output:
root@debian:/home/debian/Downloads/new/infomap-1-beta/examples/python# python3 ./simple.py 
Traceback (most recent call last):
  File "./simple.py", line 3, in <module>
    myInfomap = infomap.Infomap("--two-level --verbose")
AttributeError: module 'infomap' has no attribute 'Infomap'
Can you please help me to solve this problem?
Thanks in advance.

**Comment by antoneri** [comment]
Which version of Infomap? I can't reproduce this on `1.0.0-beta.50`.
Check with `infomap -v`.
