### ISSUE TITLE
Unrecognized option: '--zero-based-numbering' in 1.0.0-beta.54

### ISSUE THREAD

**Issue by VioletM** [mapequation/infomap#65]
I am using python 3.6 and infomap 1.0.0-beta.54. The option '--zero-based-numbering' is unrecognized as well as '-z'. Please, put it back. Thanks!

**Comment by danieledler** [comment]
Hi, the reason we had this option in the v0.x version is that we relied on indexing the nodes in a vector, thus requiring contiguous node numbering from zero. For input files however, we assumed by default that node numbering starts from 1, and internally we subtracted 1 to get zero-based indexing. This doesn't work if it already starts from zero, and in that case we required the -z/--zero-based-numbering flag.

This requirement is no longer necessary in v1, as we index the nodes by their id with a map. This allows arbitrary numbering and gaps which makes it more flexible and easy to use for different inputs. Does it make sense or do I miss your point?
