### ISSUE TITLE
Need command line or test examples with results to check install works as expected. 

### ISSUE THREAD

**Issue by wolfiex** [mapequation/infomap#69]
**Describe the bug**
No command line example tests to check that infomap works - it seems to not want to separate items into their individual clusters

**To Reproduce**
There are no examples to reproduce. Note these need to have results for comparison too. 

**Desktop (please complete the following information):**
pip install of 1.0.0-beta.58 in linux

**Comment by antoneri** [comment]
We have discussed adding example networks and tests (mostly for dev purposes and regression tracking).

We have made an effort to include well documented example networks in [Infomap Online](//mapequation.org/infomap). They all show community structure, does this help?

I will close this issue for now, please reopen it if you have any questions!
