### ISSUE TITLE
Example multiplex run does not produce any clusters

### ISSUE THREAD

**Issue by wolfiex** [mapequation/infomap#70]
**Describe the bug**
The multiplex [example format](https://www.mapequation.org/code.html#Multiplex-format), when run, does not produce and clusters. This happens both locally and on the online https://www.mapequation.org/infomap/

**To Reproduce**
Paste  into the online infomap alg. 
```# A network in a general multiplex format
# layer node layer node [weight]
1 1 1 2 2
1 1 2 2 1
1 2 1 1 1
1 2 2 2 1
2 2 1 3 1
2 3 2 2 1
2 4 2 1 2
2 4 1 2 1
```

**Comment by antoneri** [comment]
Thanks for submitting an issue!

The example is too well-connected. Changing the last line to
`2 4 1 4 1` produces two clusters.

We'll update the documentation for v1 with a better example.
