### ISSUE TITLE
Conda release

### ISSUE THREAD

**Issue by vinisalazar** [mapequation/infomap#88]
Hi,

I'm using this package as a dependency to [another one I have forked](http://github.com/vinisalazar/PopCOGenT/). I'm trying to build a conda release for it and being able to install infomap through conda would help me.

I'll be attempting one myself but if others are keen, it would be extremely helpful.

Thank you for any assistance you can provide,

V

**Comment by antoneri** [comment]
Yes, this is on the roadmap after the 1.0 release!

**Comment by vinisalazar** [comment]
I've managed through a `meta.yaml` file, but I'm having difficulties copying the `./Infomap` binary after the `make` command.

**Comment by vinisalazar** [comment]
@danieledler @antoneri shall I tag one of you as recipe maintainer?

**Comment by antoneri** [comment]
I think I'll leave this one to @danieledler, he's the lead!

**Comment by vinisalazar** [comment]
Opened a PR in @conda-forge , tagged above

**Comment by vinisalazar** [comment]
@danieledler The recipe was merged to staged-recipes!
