### ISSUE TITLE
'pip install infomap';  No module named 'package_meta'

### ISSUE THREAD

**Issue by AlexChaloner** [mapequation/infomap#95]
Is the infomap package on PyPi built properly?

Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\alexc\AppData\Local\Temp\pip-install-bw0bw2ol\infomap\setup.py", line 10, in <module>
        import package_meta
    ModuleNotFoundError: No module named 'package_meta'

**Comment by danieledler** [comment]
@AlexChaloner Thanks for the heads up! It seems we missed something in the latest update, I will take a look!

**Comment by antoneri** [comment]
Just for clarification: which version of Python are you running? (check `python --version`)

**Comment by AlexChaloner** [comment]
Thanks guys!

I'm running Python 3.6.8

**Comment by danieledler** [comment]
We have uploaded a fix in version 1.0.1, can you please try now and see if it solves the problem for you?

**Comment by AlexChaloner** [comment]
The package_meta is now fixed, and on Ubuntu the pip install succeeds.

However on Windows when attempting 'pip install infomap' I receive many warnings about possible loss of data followed by errors about 'min' not a member of 'std':

    ./src\io\Network.cpp(331): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\io\Network.cpp(332): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\io\Network.cpp(543): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\io\Network.cpp(544): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\io\Network.cpp(765): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    ./src\io\Network.cpp(767): error C2039: 'min': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\fstream(26): note: see declaration of 'std'
    ./src\io\Network.cpp(767): error C3861: 'min': identifier not found
    ./src\io\Network.cpp(768): error C2039: 'min': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\fstream(26): note: see declaration of 'std'
    ./src\io\Network.cpp(768): error C3861: 'min': identifier not found
    ./src\io\Network.cpp(945): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\alexc\downloads\rl project\wamdp\.venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alexc\\AppData\\Local\\Temp\\pip-install-ovp4ej91\\infomap\\setup.py'"'"'; __file__='"'"'C:\\Users\\alexc\\AppData\\Local\\Temp\\pip-install-ovp4ej91\\infomap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alexc\AppData\Local\Temp\pip-record-oxajze_h\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\alexc\downloads\rl project\wamdp\.venv\include\site\python3.7\infomap' Check the logs for full command output. 

I am using Windows 10, with Visual Studio 2019.

Googling says about including <algorithm> in a header file?

Thanks again!

**Comment by danieledler** [comment]
Thanks for testing, and nice to hear that the package_meta fix works now. We didn't get this new problem when we tried pip install on our Windows computer but with your help to test we can try some potential solutions. I created a new issue where we can continue the discussion!

Thanks!
