### ISSUE TITLE
Error compiling on Windows: 'min': is not a member of 'std'

### ISSUE THREAD

**Issue by danieledler** [mapequation/infomap#97]
The package_meta is now fixed, and on Ubuntu the pip install succeeds.

However on Windows when attempting 'pip install infomap' I receive many warnings about possible loss of data followed by errors about 'min' not a member of 'std':

    ./src\io\Network.cpp(331): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\io\Network.cpp(332): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\io\Network.cpp(543): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\io\Network.cpp(544): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
    ./src\io\Network.cpp(765): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    ./src\io\Network.cpp(767): error C2039: 'min': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\fstream(26): note: see declaration of 'std'
    ./src\io\Network.cpp(767): error C3861: 'min': identifier not found
    ./src\io\Network.cpp(768): error C2039: 'min': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\fstream(26): note: see declaration of 'std'
    ./src\io\Network.cpp(768): error C3861: 'min': identifier not found
    ./src\io\Network.cpp(945): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\alexc\downloads\rl project\wamdp\.venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alexc\\AppData\\Local\\Temp\\pip-install-ovp4ej91\\infomap\\setup.py'"'"'; __file__='"'"'C:\\Users\\alexc\\AppData\\Local\\Temp\\pip-install-ovp4ej91\\infomap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alexc\AppData\Local\Temp\pip-record-oxajze_h\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\alexc\downloads\rl project\wamdp\.venv\include\site\python3.7\infomap' Check the logs for full command output. 

I am using Windows 10, with Visual Studio 2019.

Googling says about including <algorithm> in a header file?

Thanks again!

_Originally posted by @AlexChaloner in https://github.com/mapequation/infomap/issues/95#issuecomment-592183341_

**Comment by danieledler** [comment]
Hi @AlexChaloner, we have uploaded a potential fix for the error on the python test index, so can you please try that by running:
```
pip install -i https://test.pypi.org/simple/ infomap==1.0.2.post0
```

**Comment by AlexChaloner** [comment]
That works! Installed successfully.

**Comment by danieledler** [comment]
Glad to hear, and thanks for your quick feedback! We will update the main PyPI registry with the update tomorrow, so you will get the fix on subsequent `pip install --upgrade infomap`.

**Comment by danieledler** [comment]
Now we have updated the main PyPI registry with the fixed version!

**Comment by AlexChaloner** [comment]
It works! Thank you very much!
